### ISSUE TITLE
arm64 image

### ISSUE THREAD

**Issue by bunkerman** [Dark-Alex-17/managarr#20]
As the title suggests, I would need a raspberry pi compatible docker image

**Comment by Dark-Alex-17** [comment]
Ah, thanks for mentioning this! I'm putting together a list of CI/CD tasks I need to work for wider platform support and this one slipped my mind a bit. I'm hoping to get to that either some time this month or next.

**Comment by Dark-Alex-17** [comment]
I've just released the beta version with Sonarr support, and now with an arm64 image. You can use it via the `arm64` tag!
i.e.

`docker run --rm -it -v "$HOME/.config/managarr/config.yml:/root/.config/managarr/config.yml" darkalex17/managarr:arm64`

I tested this out on my Raspberry Pi's and it worked like a charm. Please let me know if you have any issues! 

Thanks for mentioning this, I'm glad I was able to get it in for the beta release.

**Comment by hollanbm** [comment]
> I've just released the beta version with Sonarr support, and now with an arm64 image. You can use it via the `arm64` tag!
> 
> i.e.
> 
> 
> 
> `docker run --rm -it -v "$HOME/.config/managarr/config.yml:/root/.config/managarr/config.yml" darkalex17/managarr:arm64`
> 
> 
> 
> I tested this out on my Raspberry Pi's and it worked like a charm. Please let me know if you have any issues! 
> 
> 
> 
> Thanks for mentioning this, I'm glad I was able to get it in for the beta release.

Instead of building a dedicated arm64 image, you should be building multi platform images instead.

This way when the image is pulled, docker will grab the correct image, for whatever platform you're using, arm64 or amd64

Here's an [example](https://github.com/hollanbm/renamarr/blob/main/.github/workflows/buildImage.yaml) from one of my projects

**Comment by Dark-Alex-17** [comment]
That was the original plan, but for whatever reason when playing with this yesterday, I was unable to get any of the buildx images to work on my Pi's. However, when I tried this, I kept getting the following errror:

`exec /usr/local/bin/managarr: exec format error`

Now when I went back and made sure the Dockerfile definition was correct, and the file had minimal changes to work with the cross project. 

So since the arm64 image is working, for the beta release, I just pushed it out and I'll work on the CI as a separate thing. I'm working on that now. :)

**Comment by bunkerman** [comment]
I'm getting that error
`managarr The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`
I have a raspberry 3b+ with raspbian 64 bit running the arrr stack

**Comment by Dark-Alex-17** [comment]
Are you getting that error trying to build a multi-platform image or from the `arm64` image that's already out there?

**Comment by bunkerman** [comment]
![grafik](https://github.com/user-attachments/assets/4f2e219b-10bf-4cb7-8701-d5b7081f7552)

I pulled that version from docker hub

**Comment by Dark-Alex-17** [comment]
Whelp... Glad I just about wrapped up the bug fix so I can focus on multi-platform builds now! 😂

It shouldn't be that bad. I just needed to sleep on it before working it because, you know, sleep helps think. 

I'll start on this today.

**Comment by bunkerman** [comment]
Thanks really appreciate it and I can give feedback on the multiplatform image.

**Comment by Dark-Alex-17** [comment]
Took me a minute, but I did manage to get multi-platform builds working and they do work on my Raspberry Pi 3b as well. The issue was that the base image I was using to build was explicitly an `x86_64-musl` image. Updated the build steps and Dockerfile and tested out the job and it's finally working! 

Once I finish this test run of the workflow, I'm going to kick off a release since there's a lot of bugfixes I want to get out before Christmas so I don't have to worry about them later. :smile:

**Comment by Dark-Alex-17** [comment]
@hollanbm Thanks for your example, it helped me get `buildx` configured just right for the multi-platform builds to work. I appreciate you!

**Comment by hollanbm** [comment]
> @hollanbm Thanks for your example, it helped me get `buildx` configured just right for the multi-platform builds to work. I appreciate you!

Glad to hear you got it sorted out 😄

**Comment by Dark-Alex-17** [comment]
@bunkerman , since this is your ticket, I want to be sure your particular request is resolved. Let me know if the multi-platform image works for you and if the issue can be closed or if you think I should add more/change something else.

**Comment by bunkerman** [comment]
> @bunkerman , since this is your ticket, I want to be sure your particular request is resolved. Let me know if the multi-platform image works for you and if the issue can be closed or if you think I should add more/change something else.

Yessir, it's working now on rpi3b+ and raspbian 64bit. thx!
