### ISSUE TITLE
add/cancel button positioning

### ISSUE THREAD

**Issue by duviful** [Dark-Alex-17/managarr#8]
Hello, I find this app very useful. Great idea.

I wanted to express doubts about the positioning of the add/cancel button during a movie add or an edit.

The interface doesn't scale and it took me some time to find out about these buttons. My terminal was not on full screen and the buttons were simply hidden/cut out. 

Well now that I found them, it will not be a problem for me anymore, but for new users, that may cause some confusion.

You might add additional keyboard shortcut instead of scaling the interface to make the buttons pop up in small sized terminals.

Thanks and best.

**Comment by Dark-Alex-17** [comment]
I'm glad you like it! Thanks for the compliments! ☺️

Hmm... The original idea behind the terminal sizing checks was to mitigate this exact situation. I neglected to think of font sizing that would make scaling more challenging. 

Keyboard shortcuts sound like an easy fix for the time being. What would you recommend? My thoughts are

- `Esc` - Cancel/close modal
- `Ctrl-s` - Confirm/accept modal

The reason I think something like `Ctrl-s` is because `Enter` is currently used to select/modify whatever field is currently highlighted. 

I feel like there's a better shortcut than `Ctrl-s` to accept a modal, but I'm struggling to think of something. 

What are your thoughts?

**Comment by duviful** [comment]
I think what you proposed is good. `ctrl-s` is already a well known shortcut for saving operation, which makes sense since we want to "save" the adds/edits.

You already introduce `ctrl-r` for refresh, the usage of combined keys is cleared.

Should be enough for now. 😊

**Comment by Dark-Alex-17** [comment]
Sounds good to me then! I'll start on that now. I've also added a tech debt ticket for myself to my Wekan board to allow dynamic adjustments to modals based on terminal sizing to mitigate this issue further in the future. 

Thanks for your input!

**Comment by Dark-Alex-17** [comment]
This is now available in v0.2.0. Thanks for your input!
